// 모든 도메인 예외와 시스템 에러를 한 곳에서 식별 가능한 enum.
// 프론트는 message 문자열이 아닌 이 코드로 분기해야 한다.
// (메시지는 카피 변경/i18n으로 흔들리지만 코드는 계약처럼 유지된다.)
//
// 명명 규칙: <DOMAIN>_<상태>. 도메인 prefix로 grep/검색 용이성을 확보.
export enum ErrorCode {
  // ── 공통 ──
  INTERNAL_ERROR = "INTERNAL_ERROR",
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // ── Auth ──
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_IN_USE = "AUTH_EMAIL_IN_USE",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_NOT_AUTHENTICATED = "AUTH_NOT_AUTHENTICATED",

  // ── Todo ──
  TODO_NOT_FOUND = "TODO_NOT_FOUND",
  TODO_LOAD_FAILED = "TODO_LOAD_FAILED",
  TODO_DELETED_OR_TRASHED = "TODO_DELETED_OR_TRASHED",
  TODO_ALREADY_TRASHED = "TODO_ALREADY_TRASHED",
  TODO_DEFER_TOMORROW_TODAY_ONLY = "TODO_DEFER_TOMORROW_TODAY_ONLY",
  TODO_DEFER_NEXT_WEEK_THIS_WEEK_ONLY = "TODO_DEFER_NEXT_WEEK_THIS_WEEK_ONLY",
  TODO_PARENT_INVALID = "TODO_PARENT_INVALID",
  TODO_REORDER_INVALID = "TODO_REORDER_INVALID",

  // ── Tag ──
  TAG_NOT_FOUND = "TAG_NOT_FOUND",
  TAG_DUPLICATE = "TAG_DUPLICATE",
  TAG_NAME_IN_USE = "TAG_NAME_IN_USE",
}
